`ifndef rhuMacros__svh
`define rhuMacros__svh
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-19 08:23:57 -0500
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

`define rhudbg_register(ctype) \
	begin \
		RhuDebugPool _pool_ = RhuDebugPool::getGlobalPool(); \
		_pool_.register(this,`"ctype`"); \
	end
`define rhudbg(id,msg) \
	begin \
		RhuDebugPool _pool_ = RhuDebugPool::getGlobalPool(); \
		_pool_.processDisplayID(id,this); \
		`uvm_info(id,msg,UVM_LOW) \
	end

`endif
