`ifndef rhudbg__sv
`define rhudbg__sv
/************************************************************************************/
// Author: RyanHunter
// Created: 2022-12-19 08:23:57 -0500
// Description:
// This file is automatically generated by MDC-v2, any issues found
// here should be modified in its source markdown document the same
// dir structure in Git/Obsidian/...
/************************************************************************************/

`include "uvm_macros.svh"
package rhudbg;
	import uvm_pkg::*;
	`include "rhuMacros.svh"
	`include "rhuDebugger.svh"
endpackage

`endif
